name: IAM Deployement

on:
  workflow_dispatch:
    inputs:
      docker-hand-on:
        type: choice
        description: 'Trigger deployment for docker-hand-on project'
        required: true
        options:
          - Create_IAM_Role
          - Delete_IAM_Role
      operation:
        type: choice
        description: 'Select operation type'
        required: true
        options:
          - Create
          - Delete

permissions:
  contents: read
  id-token: write

jobs:
  Create_IAM_Role:
    name: Deploy IAM Changes
    if: ${{ github.event.inputs.docker-hand-on == 'Create_IAM_Role' && github.event.inputs.operation == 'Create' }}
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::529875232668:role/tf-deployer-role
          aws-region: us-east-1

      - name: Check identity
        run: aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5

      - name: Verify Terraform version
        working-directory: iam
        run: terraform --version

      - name: Terraform Init
        working-directory: iam
        run: |
          terraform init \
            -backend-config="bucket=${{ vars.TERRAFORM_DEPLOYMENT_BUCKET }}" \
            -backend-config="key=${{ vars.TERRAFORM_STATE_KEY }}"

      - name: Terraform Validate
        working-directory: iam
        run: terraform validate

      - name: Terraform Plan
        working-directory: iam
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: iam
        run: terraform apply -auto-approve tfplan 